---
# Ente Configuration Variables
cluster_name: "ente-ansible"
domain: "localhost"
museum_port: 8090

# Web Application Ports
photos_port: 3000
accounts_port: 3001
albums_port: 3002
auth_port: 3003
cast_port: 3004

# Database Configuration
db_password: "your_secure_db_password"

# Security Keys (32+ characters required)
jwt_secret: "jwt_secret_key_32_chars_minimum_length_here_123456789"
enc_key: "encryption_key_32_chars_minimum_length_here_123456789"
hash_key: "hash_key_32_chars_minimum_length_here_123456789012"

# S3 Storage Configuration
s3_key: "minioadmin"
s3_secret: "minioadmin123"